services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - ./assets:/app/assets  # Mount local assets to /app/assets
      - ./uploads:/app/uploads  # Mount for user uploads and outputs
    environment:
      - ENV=production

  worker:
    build: .
    command: celery -A app.tasks.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - ./assets:/app/assets  # Same mount for assets
      - ./uploads:/app/uploads  # Same mount for uploads
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_IGNORE_RESULT=false
    deploy:
      resources:
        limits:
          memory: 8g  # Give it 8GB
          cpus: "2.0"  # 2 CPUs

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"