version: "3.8"

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - ENV=production

  worker:
    build: .
    command: celery -A app.tasks.celery_app.celery_app worker --loglevel=info
    depends_on:
      - redis
    volumes:
      - .:/app
    environment:
      - ENV=production

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"
